# This is a basic workflow to help you get started with Actions
name: CI

on:
  push:
    branches:
      - master
      - staging1
      - staging2
      - staging3
      - staging4
      - staging5
      - staging6
jobs:
  build:
    runs-on: ubuntu-latest
    env:
        BRANCH: github.ref

    steps:
      - uses: actions/checkout@v2

      - name: test
        run echo ${BRANCH}

